import Head from "next/head";
// import Image from 'next/image'
import Script from "next/script";
import styles from "../styles/Home.module.css";
// import { Component } from 'react'
import { attributes, react as HomeContent } from "../content/cats.md";

export default function Home() {
  const { title, date, cats } = attributes;

  return (
    <div className={styles.container}>
      <Head>
        <title>[Experimental] Netlify CMS with Next Js - Cats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></Script>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">{title}</a>
        </h1>

        <p className={styles.description}>Last Update on {date}</p>

        <div className={styles.grid}>
          {cats.map((cat, k) => (
            <a key={k} className={styles.card}>
              <h2>{cat.name} &rarr;</h2>
              <p>{cat.description}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by {"Vercel"}
        </a>
      </footer>
    </div>
  );
}
